sudo: required
services:
  - docker

before_install:
  - docker build -t myates/ww-f-dev -f Dockerfile.dev .
  - echo docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

script:
  - docker run -e CI=true myates/ww-f-dev npm run test
  - docker build -t myates/ww-frontend .
  - docker push myates/ww-frontend:latest
