sudo: required
services:
  - docker

before_install:
  - echo docker login -u "$DOCKER_USER" -P "DOCKER_PASS"
  - docker build -t myates/ww-f-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true myates/ww-f-dev npm run test
  - docker build -t myates/wallwander:frontend .
  - docker push myates/wallwander:frontend
